eq_num = int(input('enter the number of equations'))
eq_val =int(input('enter the values of the equation on the L.H.S without the variables'))
eq_sol = int(input('enter the values of the rquation on the R.H.S'))
#A = eq_val.split()
#B = eq_sol.split()
a = list(map(int, str(eq_val)))
b = list(map(int, str(eq_sol)))
print(a)
print(b)